// pages/terms.js
// GemPredict — Terms of Use page

const C = {
  cream: "#f5f3ee", white: "#ffffff", ink: "#0e0f0c",
  inkMid: "#3d3d39", inkSoft: "#7a7a74", border: "#e2dfd8",
  gold: "#c9a84c",
};

const SECTIONS = [
  {
    title: "Acceptance of Terms",
    body: "By accessing or using GemPredict (gempredict.com), you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, please do not use the service. These terms apply to all visitors, users, and anyone who accesses or uses GemPredict.",
  },
  {
    title: "Informational Purposes Only",
    body: "GemPredict is provided for informational and educational purposes only. The grading estimates, value ranges, and recommendations generated by GemPredict are AI-generated outputs based on general market knowledge. They are not financial advice, investment advice, or a guarantee of any card's market value. You should not make buying, selling, or grading decisions based solely on GemPredict's output without conducting your own independent research.",
  },
  {
    title: "AI-Generated Estimates May Be Inaccurate",
    body: "GemPredict uses an AI language model to generate predictions. These predictions may be inaccurate, incomplete, out of date, or not applicable to your specific card's condition, variant, printing, or regional market. Card values fluctuate constantly based on market conditions, pop report changes, player performance, and other factors that an AI model cannot reliably account for in real time. Always verify estimates against current market data before making any decisions.",
  },
  {
    title: "No Affiliation with PSA or Other Grading Companies",
    body: "GemPredict is an independent tool and is not affiliated with, endorsed by, sponsored by, or connected to PSA (Professional Sports Authenticator), Beckett Grading Services, CGC, or any other grading company. References to PSA grading values or grades are for informational context only and do not represent official PSA pricing, policies, or assessments.",
  },
  {
    title: "No Warranties",
    body: "GemPredict is provided on an 'as is' and 'as available' basis without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, secure, or free of inaccuracies. To the fullest extent permitted by law, we disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.",
  },
  {
    title: "Limitation of Liability",
    body: "To the maximum extent permitted by applicable law, GemPredict and its operators shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the service, reliance on AI-generated estimates, or any grading, buying, or selling decisions made based on information obtained through GemPredict. Your use of this service is entirely at your own risk.",
  },
  {
    title: "Use at Your Own Risk",
    body: "You acknowledge that grading fees, shipping costs, and market timing involve real financial risk. GemPredict does not assume any responsibility for financial outcomes resulting from decisions influenced by its outputs. Treat all estimates as rough guidance only, and always conduct your own due diligence before submitting cards for grading or making purchasing decisions.",
  },
  {
    title: "Rate Limits and Fair Use",
    body: "GemPredict imposes usage limits (currently 5 predictions per hour per user) to ensure fair access for all users. Attempts to circumvent these limits, abuse the service, or use GemPredict for commercial scraping or data harvesting are prohibited and may result in access being suspended.",
  },
  {
    title: "Intellectual Property",
    body: "All content, design, branding, and code associated with GemPredict are the intellectual property of GemPredict and its operators. You may not reproduce, redistribute, or commercially exploit any part of this service without express written permission.",
  },
  {
    title: "Changes to These Terms",
    body: "We reserve the right to update these Terms of Use at any time. Changes will be reflected by updating the date at the bottom of this page. Continued use of GemPredict following any changes constitutes your acceptance of the updated terms.",
  },
  {
    title: "Governing Law",
    body: "These terms shall be governed by and construed in accordance with applicable law. Any disputes arising under these terms shall be resolved in the appropriate jurisdiction.",
  },
  {
    title: "Contact",
    body: "If you have any questions about these Terms of Use, please contact us via the contact link in the footer.",
  },
];

export default function Terms() {
  return (
    <div style={{ fontFamily: "'Outfit', system-ui, sans-serif", background: C.cream, minHeight: "100vh", color: C.ink }}>
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,900;1,700&family=Outfit:wght@300;400;500;600&display=swap" rel="stylesheet" />
      <style>{`* { box-sizing: border-box; } body { margin: 0; }`}</style>

      {/* NAV */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 200,
        background: "rgba(245,243,238,0.95)", backdropFilter: "blur(16px)",
        borderBottom: "1px solid " + C.border,
        height: 62, display: "flex", alignItems: "center",
        padding: "0 1.5rem",
      }}>
        <a href="/" style={{ fontFamily: "'Playfair Display', serif", fontSize: "1.35rem", fontWeight: 900, letterSpacing: "-0.01em", textDecoration: "none", color: C.ink }}>
          Gem<span style={{ color: C.gold }}>Predict</span>
        </a>
        <a href="/" style={{ marginLeft: "auto", fontSize: "0.875rem", fontWeight: 500, color: C.inkSoft, textDecoration: "none" }}>
          Back to Home
        </a>
      </nav>

      {/* CONTENT */}
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "5rem 1.5rem 6rem" }}>
        <p style={{ fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: C.gold, marginBottom: "0.6rem" }}>
          Legal
        </p>
        <h1 style={{
          fontFamily: "'Playfair Display', serif",
          fontSize: "clamp(2rem, 4vw, 3rem)",
          fontWeight: 900, letterSpacing: "-0.025em", lineHeight: 1.1,
          marginBottom: "0.75rem",
        }}>
          Terms of Use
        </h1>
        <p style={{ fontSize: "0.875rem", color: C.inkSoft, marginBottom: "3.5rem" }}>
          Last updated: January 2026
        </p>

        <div style={{ display: "flex", flexDirection: "column", gap: "2.5rem" }}>
          {SECTIONS.map(function(s) {
            return (
              <div key={s.title}>
                <h2 style={{
                  fontFamily: "'Playfair Display', serif",
                  fontSize: "1.25rem", fontWeight: 700,
                  marginBottom: "0.75rem", color: C.ink,
                }}>
                  {s.title}
                </h2>
                <p style={{ fontSize: "0.95rem", color: C.inkMid, lineHeight: 1.85 }}>
                  {s.body}
                </p>
              </div>
            );
          })}
        </div>
      </div>

      {/* FOOTER */}
      <div style={{ background: C.ink, borderTop: "1px solid rgba(255,255,255,0.07)", padding: "2rem 1.5rem" }}>
        <div style={{ maxWidth: 720, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "0.75rem" }}>
          <span style={{ fontFamily: "'Playfair Display', serif", fontSize: "1.1rem", fontWeight: 900, color: "#fff" }}>
            Gem<span style={{ color: C.gold }}>Predict</span>
          </span>
          <div style={{ display: "flex", gap: "1.5rem" }}>
            {[["Privacy Policy", "/privacy"], ["Terms of Use", "/terms"], ["Contact", "#"]].map(function(l) {
              return (
                <a key={l[0]} href={l[1]} style={{ fontSize: "0.75rem", color: "rgba(255,255,255,0.35)", textDecoration: "none" }}>
                  {l[0]}
                </a>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
